package FrontLine;


import OfficerProfile.OfficerProfile;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import DataBase.DataBase;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOH
 */
public class Accept_Post extends javax.swing.JFrame {
    DataBase dbs = new DataBase();
    
    Connection con,con1 = null;
    PreparedStatement ps,ps1 = null;
    ResultSet rs,rs1 = null;
    
    String DBuser = dbs.UserDB.getText();
    String DBpass = dbs.PassDB.getText();
    String DBName = dbs.nameDB.getText();
    
    String str;
    int x,y;
    
    public Accept_Post() {
        initComponents();
        this.setLocationRelativeTo(null);
//        jTextArea1.setBounds(161,23,45,23);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Frontline Officer Case Accept and Post");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(153, 0, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Suspected ID");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 220, 20);

        ID.setBackground(new java.awt.Color(255, 255, 51));
        ID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 0));
        ID.setBorder(null);
        ID.setOpaque(false);
        jPanel2.add(ID);
        ID.setBounds(224, 0, 240, 30);

        jTextField2.setBackground(new java.awt.Color(255, 204, 0));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(24, 255, 0));
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(220, 220, 234, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Wereda");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 220, 220, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Suspected Name");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 150, 220, 30);

        jTextField3.setBackground(new java.awt.Color(255, 204, 0));
        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(24, 255, 0));
        jTextField3.setBorder(null);
        jTextField3.setOpaque(false);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(220, 150, 234, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("City");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 290, 220, 30);

        jTextField4.setBackground(new java.awt.Color(255, 204, 0));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(24, 255, 0));
        jTextField4.setBorder(null);
        jTextField4.setOpaque(false);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(220, 290, 234, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nationality");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 370, 220, 30);

        jTextField5.setBackground(new java.awt.Color(255, 204, 0));
        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(24, 255, 0));
        jTextField5.setBorder(null);
        jTextField5.setOpaque(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5);
        jTextField5.setBounds(220, 370, 234, 30);

        jLabel8.setBackground(new java.awt.Color(255, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Write Description here:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(448, 13, 530, 26);

        jTextArea1.setColumns(1);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(1);
        jTextArea1.setTabSize(1);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 3));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(451, 90, 526, 520);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Phone number");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 450, 220, 30);

        jTextField6.setBackground(new java.awt.Color(255, 204, 0));
        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(24, 255, 0));
        jTextField6.setBorder(null);
        jTextField6.setOpaque(false);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(220, 450, 234, 30);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Photo");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 540, 220, 30);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(224, 510, 220, 155);

        jLabel23.setBackground(new java.awt.Color(255, 0, 0));
        jLabel23.setOpaque(true);
        jPanel2.add(jLabel23);
        jLabel23.setBounds(220, 30, 248, 5);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CaseID");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.setOpaque(true);
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, 90, 220, 30);

        jTextField8.setBackground(new java.awt.Color(255, 204, 0));
        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(24, 255, 0));
        jTextField8.setBorder(null);
        jTextField8.setOpaque(false);
        jPanel2.add(jTextField8);
        jTextField8.setBounds(220, 90, 234, 30);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontLine/post.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13);
        jLabel13.setBounds(600, 620, 220, 50);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontLine/lodsm.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14);
        jLabel14.setBounds(280, 40, 120, 40);

        jLabel17.setBackground(new java.awt.Color(255, 0, 0));
        jLabel17.setOpaque(true);
        jPanel2.add(jLabel17);
        jLabel17.setBounds(220, 120, 230, 4);

        jLabel18.setBackground(new java.awt.Color(255, 0, 0));
        jLabel18.setOpaque(true);
        jPanel2.add(jLabel18);
        jLabel18.setBounds(220, 180, 230, 4);

        jLabel19.setBackground(new java.awt.Color(255, 0, 0));
        jLabel19.setOpaque(true);
        jPanel2.add(jLabel19);
        jLabel19.setBounds(220, 250, 230, 4);

        jLabel20.setBackground(new java.awt.Color(255, 0, 0));
        jLabel20.setOpaque(true);
        jPanel2.add(jLabel20);
        jLabel20.setBounds(220, 320, 230, 4);

        jLabel21.setBackground(new java.awt.Color(255, 0, 0));
        jLabel21.setOpaque(true);
        jPanel2.add(jLabel21);
        jLabel21.setBounds(220, 400, 230, 4);

        jLabel22.setBackground(new java.awt.Color(255, 0, 0));
        jLabel22.setOpaque(true);
        jPanel2.add(jLabel22);
        jLabel22.setBounds(220, 480, 230, 4);

        jLabel3.setBackground(new java.awt.Color(255, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainInvestigator/bighomeab.jpg"))); // NOI18N
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 90, 450, 590);

        jLabel16.setBackground(new java.awt.Color(153, 0, 51));
        jLabel16.setOpaque(true);
        jPanel2.add(jLabel16);
        jLabel16.setBounds(-2, 0, 980, 90);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_48px.png"))); // NOI18N
        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if(jTextField8.getText().equals("") || jTextArea1.getText().equals("") || ID.getText().equals("") || jTextField3.getText().equals("") || jTextField2.getText().equals("") || jTextField4.getText().equals("") || jTextField5.getText().equals("") || jTextField6.getText().equals(""))
{
      JOptionPane.showMessageDialog(null, "Fill nessessery fields");
}
else
{      
     try {
            //Validate Employee ID correct or not
            String str_upd = "SELECT suspectID FROM caseone WHERE suspectID=?";
            con1 = DriverManager.getConnection(DBName, DBuser,DBpass);
            ps1 = con1.prepareStatement(str_upd);
            ps1.setString(1, ID.getText());
            rs1 = ps1.executeQuery();
        if(rs1.next() && rs1.getString("suspectID").equals(ID.getText()))
        {
            JOptionPane.showMessageDialog(null, "suspectID Already Exist Update Sequence Initiated !!");
            int resp = JOptionPane.showConfirmDialog(this, "Do you want to continue ?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(resp == JOptionPane.YES_OPTION)
                {
            //Update Case report one
                con = DriverManager.getConnection(DBName, DBuser,DBpass);
                str = "UPDATE caseone set caseID=?,suspectedname=?,wereda=?,city=?, nationality=?, phonenumber=?, description=? WHERE suspectID=?";
                ps = con.prepareStatement(str);
                ps.setString(1, jTextField8.getText());
                ps.setString(2, jTextField3.getText());
                ps.setString(3, jTextField2.getText());
                ps.setString(4, jTextField4.getText());
                ps.setString(5, jTextField5.getText());
                ps.setString(6, jTextField6.getText());
                ps.setString(7, jTextArea1.getText());
                ps.setString(8, ID.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Report Successfuly Updated");
                }
                else if(resp == JOptionPane.NO_OPTION)
                {
                    JOptionPane.showMessageDialog(null, "Cancled");
                }  
        }
        else
        {
            con = DriverManager.getConnection(DBName, DBuser,DBpass);
            str = "INSERT INTO caseone(caseID,suspectID,suspectedname,wereda,city,nationality,phonenumber,description) VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
            ps = con.prepareStatement(str);
            ps.setString(1, jTextField8.getText());
            ps.setString(2, ID.getText());
            ps.setString(3, jTextField3.getText());
            ps.setString(4, jTextField2.getText());
            ps.setString(5, jTextField4.getText());
            ps.setString(6, jTextField5.getText());
            ps.setString(7, jTextField6.getText());
            ps.setString(8, jTextArea1.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Report Posted Successfuly");
        }
        } catch (SQLException ex) {
            Logger.getLogger(Accept_Post.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Fill nessessery fields");

        }
}
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
       if(ID.getText().equals(""))
{
    JOptionPane.showMessageDialog(null, "Enter ID of Suspected Please !");
}
else
{
        try {
            //Validate Employee ID correct or not
            String str_upd = "SELECT ID FROM suspectreg WHERE ID=?";
            con1 = DriverManager.getConnection(DBName, DBuser,DBpass);
            ps1 = con1.prepareStatement(str_upd);
            ps1.setString(1, ID.getText());
            rs1 = ps1.executeQuery();
        if(rs1.next() && rs1.getString("ID").equals(ID.getText()))
        {
            //connection
            con = DriverManager.getConnection(DBName, DBuser,DBpass);

            String s1,s2,s3,s4,s5;

            str = "SELECT fullName,wereda,city,nationality,PhoneNumber,image from suspectreg WHERE ID=?";
                ps = con.prepareStatement(str);
                ps.setString(1, ID.getText());
                rs=ps.executeQuery();
                while(rs.next())
                    {
                        s1 = rs.getString(1);
                        s2 = rs.getString(2);
                        s3 = rs.getString(3);
                        s4 = rs.getString(4);
                        s5 = rs.getString(5);
                        jTextField3.setText(s1);
                        jTextField2.setText(s2);
                        jTextField4.setText(s3);
                        jTextField5.setText(s4);
                        jTextField6.setText(s5);
//                ps.setString(2, jTextField3.setText("fullName"));
//                ps.setString(3, jTextField2.getText());
//                ps.setString(4, jTextField4.getText());
//                ps.setString(5, jTextField5.getText());
//                ps.setString(6, jTextField6.getText());
                    byte[] imgbyt;
                    Image img;
                        imgbyt = rs.getBytes(6);
                        img = getToolkit().createImage(imgbyt);
                        Image im = img.getScaledInstance(jTextField7.getWidth(), jTextField7.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon icon = new ImageIcon(im);
                        jTextField7.setIcon(icon);
                    }
                JOptionPane.showMessageDialog(null, "Sucessfuly Loaded"); 
        }
        else
        {
            ID.setText("");
            jTextField7.setIcon(null);
            jTextField6.setText("");
            jTextField5.setText("");
            jTextField4.setText("");
            jTextField3.setText("");
            jTextField2.setText("");
            jTextArea1.setText("");
            jTextField8.setText("");
            JOptionPane.showMessageDialog(null, "Incorrect ID"); 
        }
            
                    
                } catch (SQLException ex) {
                    Logger.getLogger(OfficerProfile.class.getName()).log(Level.SEVERE, null, ex);
                }
}
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int xx,yy;
        
        xx = evt.getXOnScreen();
        yy = evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_jLabel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accept_Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accept_Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accept_Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accept_Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accept_Post().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
