package FrontLine;



import DataBase.DataBase;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOH
 */
public class Register_suspected extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    DataBase dbs = new DataBase();
    String DBuser = dbs.UserDB.getText();
    String DBpass = dbs.PassDB.getText();
    String DBName = dbs.nameDB.getText();
    
    String str;
    String w1 = null;
    int x,y;
    
    public Register_suspected() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    ButtonGroup bg = new ButtonGroup();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        swingTimerTimingSource1 = new org.jdesktop.swing.animation.timing.sources.SwingTimerTimingSource();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        wereda = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        maleR = new javax.swing.JRadioButton();
        FemaleR = new javax.swing.JRadioButton();
        natio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        job = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        pnum = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1152, 67));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Suspected Registration");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Suspected Full Name");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 150, 280, 27);

        jLabel3.setBackground(new java.awt.Color(255, 102, 0));
        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Wereda");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 400, 280, 27);

        jLabel4.setBackground(new java.awt.Color(255, 102, 0));
        jLabel4.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nationality");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(450, 30, 280, 27);

        jLabel5.setBackground(new java.awt.Color(255, 102, 0));
        jLabel5.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Suspected ID");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 30, 280, 27);

        jLabel6.setBackground(new java.awt.Color(255, 102, 0));
        jLabel6.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("City");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(790, 140, 270, 27);

        jLabel7.setBackground(new java.awt.Color(255, 102, 0));
        jLabel7.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sex");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(450, 260, 90, 32);

        jLabel8.setBackground(new java.awt.Color(255, 102, 0));
        jLabel8.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DOB");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 270, 280, 27);

        jLabel9.setBackground(new java.awt.Color(255, 102, 0));
        jLabel9.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("JOB");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(450, 140, 280, 26);

        path.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        path.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(path);
        path.setBounds(450, 344, 610, 28);

        ID.setBackground(new java.awt.Color(51, 255, 255));
        ID.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 0));
        ID.setToolTipText("");
        ID.setBorder(null);
        ID.setOpaque(false);
        jPanel2.add(ID);
        ID.setBounds(20, 60, 277, 30);

        wereda.setBackground(new java.awt.Color(51, 255, 255));
        wereda.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        wereda.setForeground(new java.awt.Color(255, 255, 0));
        wereda.setBorder(null);
        wereda.setOpaque(false);
        jPanel2.add(wereda);
        wereda.setBounds(20, 430, 280, 30);

        city.setBackground(new java.awt.Color(51, 255, 255));
        city.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 0));
        city.setBorder(null);
        city.setOpaque(false);
        jPanel2.add(city);
        city.setBounds(790, 170, 270, 30);

        maleR.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(maleR);
        maleR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        maleR.setForeground(new java.awt.Color(255, 255, 51));
        maleR.setText("Male");
        maleR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        maleR.setOpaque(false);
        maleR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRActionPerformed(evt);
            }
        });
        jPanel2.add(maleR);
        maleR.setBounds(570, 260, 90, 27);

        FemaleR.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(FemaleR);
        FemaleR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FemaleR.setForeground(new java.awt.Color(255, 255, 51));
        FemaleR.setText("Female");
        FemaleR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        FemaleR.setOpaque(false);
        FemaleR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRActionPerformed(evt);
            }
        });
        jPanel2.add(FemaleR);
        FemaleR.setBounds(690, 260, 120, 27);

        natio.setBackground(new java.awt.Color(51, 255, 255));
        natio.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        natio.setForeground(new java.awt.Color(255, 255, 0));
        natio.setBorder(null);
        natio.setOpaque(false);
        jPanel2.add(natio);
        natio.setBounds(450, 60, 280, 30);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontLine/Register.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(451, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(419, 419, 419))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 464, 1080, 85);

        job.setBackground(new java.awt.Color(51, 255, 255));
        job.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        job.setForeground(new java.awt.Color(255, 255, 0));
        job.setToolTipText("");
        job.setBorder(null);
        job.setOpaque(false);
        jPanel2.add(job);
        job.setBounds(450, 170, 277, 30);

        fullname.setBackground(new java.awt.Color(51, 255, 255));
        fullname.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        fullname.setForeground(new java.awt.Color(255, 255, 0));
        fullname.setToolTipText("");
        fullname.setBorder(null);
        fullname.setOpaque(false);
        jPanel2.add(fullname);
        fullname.setBounds(20, 180, 277, 30);

        pnum.setBackground(new java.awt.Color(51, 255, 255));
        pnum.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        pnum.setForeground(new java.awt.Color(255, 255, 0));
        pnum.setBorder(null);
        pnum.setOpaque(false);
        jPanel2.add(pnum);
        pnum.setBounds(790, 60, 270, 30);

        jLabel10.setBackground(new java.awt.Color(255, 102, 0));
        jLabel10.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Phone number");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10);
        jLabel10.setBounds(790, 30, 270, 27);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontLine/Choosephoto.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13);
        jLabel13.setBounds(690, 380, 180, 50);

        jLabel15.setBackground(new java.awt.Color(0, 255, 255));
        jLabel15.setOpaque(true);
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 90, 280, 5);

        jLabel22.setBackground(new java.awt.Color(0, 255, 255));
        jLabel22.setOpaque(true);
        jPanel2.add(jLabel22);
        jLabel22.setBounds(20, 460, 280, 5);

        jLabel16.setBackground(new java.awt.Color(0, 255, 255));
        jLabel16.setOpaque(true);
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 210, 280, 5);

        jLabel18.setBackground(new java.awt.Color(0, 255, 255));
        jLabel18.setOpaque(true);
        jPanel2.add(jLabel18);
        jLabel18.setBounds(450, 90, 280, 5);

        jLabel19.setBackground(new java.awt.Color(0, 255, 255));
        jLabel19.setOpaque(true);
        jPanel2.add(jLabel19);
        jLabel19.setBounds(790, 90, 280, 5);

        jLabel20.setBackground(new java.awt.Color(0, 255, 255));
        jLabel20.setOpaque(true);
        jPanel2.add(jLabel20);
        jLabel20.setBounds(790, 200, 280, 5);

        jLabel21.setBackground(new java.awt.Color(0, 255, 255));
        jLabel21.setOpaque(true);
        jPanel2.add(jLabel21);
        jLabel21.setBounds(450, 200, 280, 5);

        dob.setMaxSelectableDate(new java.util.Date(1609491719000L));
        dob.setMinSelectableDate(new java.util.Date(-2208956306000L));
        jPanel2.add(dob);
        dob.setBounds(20, 332, 280, 30);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontLine/susimg.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, 0, 1080, 470);

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_48px.png"))); // NOI18N
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRActionPerformed
        bg.add(maleR);
    }//GEN-LAST:event_maleRActionPerformed

    private void FemaleRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRActionPerformed
        bg.add(FemaleR);
    }//GEN-LAST:event_FemaleRActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
       if(ID.getText().equals("") || fullname.getText().equals("") || dob.getDate().equals("") || wereda.getText().equals("") || city.getText().equals("") || natio.getText().equals("") || pnum.getText().equals("") || job.getText().equals("") || path.getText().equals(""))
        {
           JOptionPane.showMessageDialog(null, "Please fill all information !!"); 
        }
        else
        {
            try {
                    con = DriverManager.getConnection(DBName,DBuser,DBpass);
                    str = "SELECT ID FROM suspectreg WHERE ID=?";
                    ps = con.prepareStatement(str);
                    ps.setString(1, ID.getText());
                    rs = ps.executeQuery();
                    if(rs.next() && rs.getString("ID").equals(ID.getText()))
                    {
                      JOptionPane.showMessageDialog(null, "ID Already In Use");  
                    }
                    else
                    {

                    con = DriverManager.getConnection(DBName,DBuser,DBpass);
                    str = "INSERT INTO suspectreg(ID,fullName,DOB,wereda,city,nationality,PhoneNumber,job,Sex,image) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                    ps = con.prepareStatement(str);
                    ps.setString(1, ID.getText());
                    ps.setString(2, fullname.getText());
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String birthdate = sdf.format(dob.getDate());
                    ps.setString(3, birthdate);
                    ps.setString(4, wereda.getText());
                    ps.setString(5, city.getText());
                    ps.setString(6, natio.getText());
                    ps.setString(7, pnum.getText());
                    ps.setString(8, job.getText());
                    if(maleR.isSelected())
                    {
                        ps.setString(9, maleR.getText());
                    }
                    else
                    {
                        ps.setString(9, FemaleR.getText());
                    }


                    try {
                        InputStream strm = new FileInputStream(new File(w1));
                        ps.setBlob(10, strm);
                        ps.executeUpdate();
                        Frontline_mainpage pl = new Frontline_mainpage();
                        ImageIcon i = new ImageIcon();
                        pl.pimage.setIcon(i);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Register_suspected.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    //            rs = ps.executeQuery();
                    //            if(rs.next())
                    {
                        JOptionPane.showMessageDialog(null, "Successfuly Registered");
                    }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Register_suspected.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        JFileChooser choose = new JFileChooser();
        choose.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = choose.showSaveDialog(getParent());
        if(result==JFileChooser.APPROVE_OPTION)
        {
            File selectedfile = choose.getSelectedFile();
            w1 = selectedfile.getAbsolutePath();
            path.setText(w1);

        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int xx,yy;
        
        xx = evt.getXOnScreen();
        yy = evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_jLabel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_suspected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_suspected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_suspected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_suspected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_suspected().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FemaleR;
    private javax.swing.JTextField ID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField city;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField job;
    private javax.swing.JRadioButton maleR;
    private javax.swing.JTextField natio;
    private javax.swing.JTextField path;
    private javax.swing.JTextField pnum;
    private org.jdesktop.swing.animation.timing.sources.SwingTimerTimingSource swingTimerTimingSource1;
    private javax.swing.JTextField wereda;
    // End of variables declaration//GEN-END:variables
}
