/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataBase;

/**
 *
 * @author JOH
 */
public class DataBase extends javax.swing.JFrame {
        
    public DataBase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserDB = new javax.swing.JTextField();
        PassDB = new javax.swing.JTextField();
        nameDB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        UserDB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UserDB.setText("root");
        getContentPane().add(UserDB);
        UserDB.setBounds(302, 42, 301, 28);

        PassDB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(PassDB);
        PassDB.setBounds(302, 103, 301, 28);

        nameDB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameDB.setText("jdbc:mysql://localhost:3306/javahospital");
        nameDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameDBActionPerformed(evt);
            }
        });
        getContentPane().add(nameDB);
        nameDB.setBounds(302, 170, 301, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DBuser");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(64, 45, 149, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DBPassword");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(64, 106, 149, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DBname");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(64, 173, 149, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBase().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField PassDB;
    public javax.swing.JTextField UserDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField nameDB;
    // End of variables declaration//GEN-END:variables
}
