package Admin;



import DataBase.DataBase;
import FrontLine.Frontline_mainpage;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOH
 */
public class AdminPage extends javax.swing.JFrame {

    Connection con,con1 = null;
    PreparedStatement ps,ps1 = null;
    ResultSet rs,rs1= null;
    
    DataBase dbs = new DataBase();
    String DBuser = dbs.UserDB.getText();
    String DBpass = dbs.PassDB.getText();
    String DBName = dbs.nameDB.getText();
    
    String str,str1;
    String pathofimage = null;
    int x,y;
    public AdminPage() {
        initComponents();
        this.setLocationRelativeTo(null);
          jPanel5.setVisible(false);
          jPanel4.setVisible(false);
          jPanel7.setVisible(false);
          jPanel10.setVisible(false);
          jPanel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        apimage = new javax.swing.JLabel();
        APname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        rSButtonIconD1 = new rojerusan.RSButtonIconD();
        rSButtonIconD2 = new rojerusan.RSButtonIconD();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        rSButtonIconD3 = new rojerusan.RSButtonIconD();
        jLabel39 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        userinput = new javax.swing.JTextField();
        wered = new javax.swing.JTextField();
        confirmpass = new javax.swing.JPasswordField();
        passwordinput = new javax.swing.JPasswordField();
        city = new javax.swing.JTextField();
        maleR = new javax.swing.JRadioButton();
        FemaleR = new javax.swing.JRadioButton();
        regdate1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nationality = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        phonenumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        comboch = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        apimage.setBackground(new java.awt.Color(255, 255, 255));
        apimage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        apimage.setOpaque(true);

        APname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        APname.setText("User Name ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Admin Profile");

        jl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl.setText("Admin Name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1336, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jl)
                        .addGap(30, 30, 30)
                        .addComponent(APname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apimage, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(apimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(APname)
                    .addComponent(jl))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rage Italic", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Robe Police Statation ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 480, 47));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Admin/t.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel2.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 480, 230));

        rSButtonIconD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/no_running_96px.png"))); // NOI18N
        rSButtonIconD1.setText("Deactivate Employee Account");
        rSButtonIconD1.setColorHover(new java.awt.Color(255, 255, 0));
        rSButtonIconD1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        rSButtonIconD1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIconD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonIconD1MouseClicked(evt);
            }
        });
        rSButtonIconD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconD1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonIconD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 480, -1));

        rSButtonIconD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontLine/plus_50px.png"))); // NOI18N
        rSButtonIconD2.setText("Create Employee Account");
        rSButtonIconD2.setColorHover(new java.awt.Color(255, 255, 0));
        rSButtonIconD2.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        rSButtonIconD2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIconD2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonIconD2MouseClicked(evt);
            }
        });
        jPanel2.add(rSButtonIconD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 480, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI Historic", 1, 48)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontLine/content_50px.png"))); // NOI18N
        jLabel35.setText("Dashboard");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 480, -1));

        jLabel36.setBackground(new java.awt.Color(255, 0, 0));
        jLabel36.setOpaque(true);
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 480, 20));

        jLabel37.setBackground(new java.awt.Color(255, 0, 0));
        jLabel37.setOpaque(true);
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 480, 10));

        rSButtonIconD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontLine/plus_50px.png"))); // NOI18N
        rSButtonIconD3.setText("BACKUP DATABASE");
        rSButtonIconD3.setColorHover(new java.awt.Color(255, 255, 0));
        rSButtonIconD3.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        rSButtonIconD3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIconD3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonIconD3MouseClicked(evt);
            }
        });
        rSButtonIconD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconD3ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonIconD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 480, -1));

        jLabel39.setBackground(new java.awt.Color(255, 0, 0));
        jLabel39.setOpaque(true);
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 480, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 255, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Registration");

        jPanel8.setBackground(new java.awt.Color(51, 255, 51));
        jPanel8.setForeground(new java.awt.Color(0, 255, 255));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Account Creation and Deactivation ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(51, 255, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        jTextField1.setBorder(null);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ID OF EMPLOYEE");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/lod acc.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Deactivate.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel38.setBackground(new java.awt.Color(255, 255, 51));
        jLabel38.setOpaque(true);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 272, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(339, 339, 339))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(472, 472, 472))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 1230, 640);

        jPanel5.setBackground(new java.awt.Color(252, 252, 174));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(102, 0, 102));
        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        jLabel4.setOpaque(true);
        jPanel5.add(jLabel4);
        jLabel4.setBounds(10, 170, 220, 32);

        jLabel5.setBackground(new java.awt.Color(102, 0, 102));
        jLabel5.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Wereda");
        jLabel5.setOpaque(true);
        jPanel5.add(jLabel5);
        jLabel5.setBounds(10, 380, 220, 32);

        jLabel6.setBackground(new java.awt.Color(102, 0, 102));
        jLabel6.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("RegDate");
        jLabel6.setOpaque(true);
        jPanel5.add(jLabel6);
        jLabel6.setBounds(680, 350, 220, 32);

        jLabel7.setBackground(new java.awt.Color(102, 0, 102));
        jLabel7.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("User Name");
        jLabel7.setOpaque(true);
        jPanel5.add(jLabel7);
        jLabel7.setBounds(10, 90, 220, 32);

        jLabel8.setBackground(new java.awt.Color(102, 0, 102));
        jLabel8.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("City");
        jLabel8.setOpaque(true);
        jPanel5.add(jLabel8);
        jLabel8.setBounds(680, 20, 220, 32);

        jLabel9.setBackground(new java.awt.Color(102, 0, 102));
        jLabel9.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sex");
        jLabel9.setOpaque(true);
        jPanel5.add(jLabel9);
        jLabel9.setBounds(680, 260, 220, 32);

        jLabel10.setBackground(new java.awt.Color(102, 0, 102));
        jLabel10.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DOB");
        jLabel10.setOpaque(true);
        jPanel5.add(jLabel10);
        jLabel10.setBounds(680, 440, 220, 32);

        jLabel11.setBackground(new java.awt.Color(102, 0, 102));
        jLabel11.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Confirm Password");
        jLabel11.setOpaque(true);
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 240, 220, 32);

        path.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel5.add(path);
        path.setBounds(36, 444, 366, 28);

        userinput.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userinput.setForeground(new java.awt.Color(0, 255, 255));
        userinput.setToolTipText("");
        userinput.setBorder(null);
        jPanel5.add(userinput);
        userinput.setBounds(258, 95, 277, 31);

        wered.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wered.setForeground(new java.awt.Color(0, 255, 255));
        wered.setBorder(null);
        jPanel5.add(wered);
        wered.setBounds(260, 380, 277, 31);

        confirmpass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        confirmpass.setForeground(new java.awt.Color(0, 255, 255));
        confirmpass.setBorder(null);
        confirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassActionPerformed(evt);
            }
        });
        jPanel5.add(confirmpass);
        confirmpass.setBounds(259, 245, 277, 31);

        passwordinput.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordinput.setForeground(new java.awt.Color(0, 255, 255));
        passwordinput.setBorder(null);
        jPanel5.add(passwordinput);
        passwordinput.setBounds(259, 173, 277, 31);

        city.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        city.setForeground(new java.awt.Color(0, 255, 255));
        city.setBorder(null);
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        jPanel5.add(city);
        city.setBounds(930, 20, 277, 31);

        maleR.setBackground(new java.awt.Color(76, 128, 18));
        maleR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        maleR.setForeground(new java.awt.Color(56, 195, 238));
        maleR.setText("Male");
        maleR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        maleR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRActionPerformed(evt);
            }
        });
        jPanel5.add(maleR);
        maleR.setBounds(920, 260, 66, 26);

        FemaleR.setBackground(new java.awt.Color(76, 128, 18));
        FemaleR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FemaleR.setForeground(new java.awt.Color(56, 195, 238));
        FemaleR.setText("Female");
        FemaleR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        FemaleR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRActionPerformed(evt);
            }
        });
        jPanel5.add(FemaleR);
        FemaleR.setBounds(1030, 260, 88, 26);

        regdate1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        regdate1.setForeground(new java.awt.Color(0, 255, 255));
        regdate1.setBorder(null);
        jPanel5.add(regdate1);
        regdate1.setBounds(930, 350, 277, 31);

        jLabel12.setBackground(new java.awt.Color(102, 0, 102));
        jLabel12.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nationality");
        jLabel12.setOpaque(true);
        jPanel5.add(jLabel12);
        jLabel12.setBounds(680, 100, 220, 32);

        nationality.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nationality.setForeground(new java.awt.Color(0, 255, 255));
        nationality.setBorder(null);
        jPanel5.add(nationality);
        nationality.setBounds(930, 100, 277, 31);

        jLabel13.setBackground(new java.awt.Color(102, 0, 102));
        jLabel13.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Phone Number");
        jLabel13.setOpaque(true);
        jPanel5.add(jLabel13);
        jLabel13.setBounds(680, 180, 220, 32);

        phonenumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phonenumber.setForeground(new java.awt.Color(0, 255, 255));
        phonenumber.setBorder(null);
        jPanel5.add(phonenumber);
        phonenumber.setBounds(930, 180, 277, 31);

        jLabel14.setBackground(new java.awt.Color(102, 0, 102));
        jLabel14.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ID");
        jLabel14.setOpaque(true);
        jPanel5.add(jLabel14);
        jLabel14.setBounds(10, 20, 220, 32);

        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(0, 255, 255));
        id.setToolTipText("");
        id.setBorder(null);
        jPanel5.add(id);
        id.setBounds(258, 25, 277, 31);

        jLabel15.setBackground(new java.awt.Color(102, 0, 102));
        jLabel15.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Type");
        jLabel15.setOpaque(true);
        jPanel5.add(jLabel15);
        jLabel15.setBounds(10, 310, 220, 32);

        comboch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comboch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frontline", "Offline", "Main Investigator", "Commander", "Admin" }));
        jPanel5.add(comboch);
        comboch.setBounds(260, 310, 276, 28);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Choosephoto.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel23);
        jLabel23.setBounds(420, 430, 170, 60);

        jLabel25.setBackground(new java.awt.Color(255, 0, 0));
        jLabel25.setOpaque(true);
        jPanel5.add(jLabel25);
        jLabel25.setBounds(260, 60, 280, 10);

        jLabel26.setBackground(new java.awt.Color(255, 0, 0));
        jLabel26.setOpaque(true);
        jPanel5.add(jLabel26);
        jLabel26.setBounds(260, 130, 280, 10);

        jLabel27.setBackground(new java.awt.Color(255, 0, 0));
        jLabel27.setOpaque(true);
        jPanel5.add(jLabel27);
        jLabel27.setBounds(260, 210, 280, 10);

        jLabel28.setBackground(new java.awt.Color(255, 0, 0));
        jLabel28.setOpaque(true);
        jPanel5.add(jLabel28);
        jLabel28.setBounds(260, 280, 280, 10);

        jLabel29.setBackground(new java.awt.Color(255, 0, 0));
        jLabel29.setOpaque(true);
        jPanel5.add(jLabel29);
        jLabel29.setBounds(260, 410, 280, 10);

        jLabel30.setBackground(new java.awt.Color(255, 0, 0));
        jLabel30.setOpaque(true);
        jPanel5.add(jLabel30);
        jLabel30.setBounds(930, 50, 280, 10);

        jLabel31.setBackground(new java.awt.Color(255, 0, 0));
        jLabel31.setOpaque(true);
        jPanel5.add(jLabel31);
        jLabel31.setBounds(930, 130, 280, 10);

        jLabel32.setBackground(new java.awt.Color(255, 0, 0));
        jLabel32.setOpaque(true);
        jPanel5.add(jLabel32);
        jLabel32.setBounds(930, 210, 280, 10);

        jLabel33.setBackground(new java.awt.Color(255, 0, 0));
        jLabel33.setOpaque(true);
        jPanel5.add(jLabel33);
        jLabel33.setBounds(930, 380, 280, 10);

        dob.setMaxSelectableDate(new java.util.Date(1609491719000L));
        dob.setMinSelectableDate(new java.util.Date(-2208956306000L));
        jPanel5.add(dob);
        dob.setBounds(930, 440, 280, 30);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/adppe.png"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel19);
        jLabel19.setBounds(0, 0, 1230, 520);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 70, 1230, 500);

        jPanel6.setBackground(new java.awt.Color(51, 255, 0));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Register.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(501, 501, 501)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(502, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 570, 1230, 80);

        jPanel10.setBackground(new java.awt.Color(51, 255, 0));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 255));
        jLabel18.setText("Account Creation and Deactivation ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel10);
        jPanel10.setBounds(0, 0, 1316, 70);

        jLabel20.setBackground(new java.awt.Color(255, 0, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_48px.png"))); // NOI18N
        jLabel20.setOpaque(true);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    ButtonGroup bg = new ButtonGroup();
    
    private void confirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void maleRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRActionPerformed
        bg.add(maleR);
    }//GEN-LAST:event_maleRActionPerformed

    private void FemaleRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRActionPerformed
        bg.add(FemaleR);
    }//GEN-LAST:event_FemaleRActionPerformed
    
    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        try {
            ShowTable();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "NO Employee Yet","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        try {
            con = DriverManager.getConnection(DBName,DBuser,DBpass);
            str = "SELECT empID FROM employee WHERE empID=?";
            ps=con.prepareStatement(str);
            ps.setString(1, jTextField1.getText());
            rs = ps.executeQuery(); 
        
            if(jTextField1.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please fill Correct Employee ID first","",JOptionPane.ERROR_MESSAGE);
            }
            
            else if(rs.next() && rs.getString("empID").equals(jTextField1.getText()))
            {
                int resp = JOptionPane.showConfirmDialog(this, "Do you want to continue ?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(resp == JOptionPane.YES_OPTION)
                {
                try
                {
                    con = DriverManager.getConnection(DBName,DBuser,DBpass);
                    str = "DELETE FROM employee WHERE empID=?";
                    ps=con.prepareStatement(str);
                    ps.setString(1, jTextField1.getText());
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Deactivated sucessfuly!");
                    ShowTable();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Please fill Correct Employee ID first");
                }
                }
                else if(resp == JOptionPane.NO_OPTION)
                {
                    JOptionPane.showMessageDialog(null, "Cancled");
                }  
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect ID");
            }
             } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        JFileChooser choose = new JFileChooser();
        choose.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = choose.showSaveDialog(getParent());
        if(result==JFileChooser.APPROVE_OPTION)
        {
            File selectedfile = choose.getSelectedFile();
            pathofimage = selectedfile.getAbsolutePath();
            path.setText(pathofimage);

        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        if(id.getText().equals("") || userinput.getText().equals("") || passwordinput.getText().equals("") || wered.getText().equals("") || city.getText().equals("") || nationality.getText().equals("") || phonenumber.getText().equals("") || dob.getDate().equals("") || path.getText().equals(""))
{
    JOptionPane.showMessageDialog(null, "Please fill all information !!","",JOptionPane.ERROR_MESSAGE);
}
else
{  
        // Registration        
        try {
           
            con = DriverManager.getConnection(DBName, DBuser,DBpass);
            str = "SELECT empID FROM employee WHERE empID=?";
            ps = con.prepareStatement(str);
            ps.setString(1, id.getText());
            rs = ps.executeQuery();
            if(rs.next() && rs.getString("empID").equals(id.getText()))
            {
              JOptionPane.showMessageDialog(null, "ID Already In Use","",JOptionPane.ERROR_MESSAGE);  
            }
            else
            {
            int x = passwordinput.getText().length();
            // day for PC
            Date d = new Date();
            String DataofR = d.toString();
//            dob.setText(DataofR);

            con = DriverManager.getConnection(DBName, DBuser,DBpass);
            str = "INSERT INTO employee(empID,username,password,type,wereda,city,nationality,phone_number,sex,regdate,dob,image) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            ps = con.prepareStatement(str);
            ps.setString(1, id.getText());
            ps.setString(2, userinput.getText());
            if((passwordinput.getText()).equals((confirmpass.getText())) && x >=9)
            {
                ps.setString(3, passwordinput.getText());
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Password Dose not match","",JOptionPane.ERROR_MESSAGE);
            }
            ps.setString(4, comboch.getSelectedItem().toString());
            ps.setString(5, wered.getText());
            ps.setString(6, city.getText());
            ps.setString(7, nationality.getText());
            ps.setString(8, phonenumber.getText());
            if(maleR.isSelected())
            {
                ps.setString(9, maleR.getText());
            }
            else
            {
                ps.setString(9, FemaleR.getText());
            }
            ps.setString(10, DataofR);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String birthdate = sdf.format(dob.getDate());
            ps.setString(11, birthdate);
            try {
                InputStream strm = new FileInputStream(new File(pathofimage));
                ps.setBlob(12, strm);
                ps.executeUpdate();
            
//                Frontline_mainpage pl = new Frontline_mainpage();
//                ImageIcon i = new ImageIcon();
//                pl.pimage.setIcon(i);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }

            //            rs = ps.executeQuery();
            //            if(rs.next())
            {
                JOptionPane.showMessageDialog(null, "Successfuly Registered");
            }
        }
                
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int xx,yy;
        
        xx = evt.getXOnScreen();
        yy = evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void rSButtonIconD2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonIconD2MouseClicked
        jPanel5.setVisible(true);
        jPanel4.setVisible(false);
        jPanel8.setVisible(true);
        jPanel7.setVisible(false);
        jPanel9.setVisible(true);
        jPanel10.setVisible(true);
        jPanel6.setVisible(true);
    }//GEN-LAST:event_rSButtonIconD2MouseClicked

    private void rSButtonIconD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonIconD1MouseClicked
        jPanel4.setVisible(true);
        jPanel5.setVisible(false);
        jPanel7.setVisible(true);
        jPanel9.setVisible(true);
    }//GEN-LAST:event_rSButtonIconD1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       for (Double i=0.0;i<=1.0;i=i+0.1)
        {
            String var = i+"";
            float f = Float.valueOf(var);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (InterruptedException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void rSButtonIconD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconD1ActionPerformed

    private void rSButtonIconD3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonIconD3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconD3MouseClicked

    private void rSButtonIconD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconD3ActionPerformed
        Backup bu = new Backup();
        bu.setVisible(true);        
    }//GEN-LAST:event_rSButtonIconD3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }
    
    public void ShowTable() throws SQLException{
        
        con = DriverManager.getConnection(DBName,DBuser,DBpass);
        String str = "SELECT * FROM employee ";
        ps=con.prepareStatement(str);
        rs=ps.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel APname;
    private javax.swing.JRadioButton FemaleR;
    public javax.swing.JLabel apimage;
    private javax.swing.JTextField city;
    private javax.swing.JComboBox<String> comboch;
    private javax.swing.JPasswordField confirmpass;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel jl;
    private javax.swing.JRadioButton maleR;
    private javax.swing.JTextField nationality;
    private javax.swing.JPasswordField passwordinput;
    private javax.swing.JTextField path;
    private javax.swing.JTextField phonenumber;
    private rojerusan.RSButtonIconD rSButtonIconD1;
    private rojerusan.RSButtonIconD rSButtonIconD2;
    private rojerusan.RSButtonIconD rSButtonIconD3;
    private rojerusan.RSPanelImage rSPanelImage1;
    private javax.swing.JTextField regdate1;
    private javax.swing.JTextField userinput;
    private javax.swing.JTextField wered;
    // End of variables declaration//GEN-END:variables
}
